### ISSUE TITLE
Update Deploy to Bluemix URL #14

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.waterConservation.starterKit#15]
Update Deploy to Bluemix URL #14
See pull request #14

**Comment by natashadsilva** [comment]
Link is still broken.. @chanskw @ibmkendrick

**Comment by chanskw** [comment]
@natashadsilva can you see if you can get it fixed please?

**Comment by natashadsilva** [comment]
Repo owners need to update the links in the  README.md  with the correct link:
`https://console.bluemix.net/devops/setup/deploy?repository=https://github.com/IBMStreams/streamsx.waterConservation.starterKit.git`

**Comment by chanskw** [comment]
Have you tried the link to see if this worked?  Do I only need to pull in the pull request?

**Comment by natashadsilva** [comment]
I tried the link that I pasted above and it at least takes you to the create toolchain page.  There are other problems with the deployment itself and even after working around those, the final app  still doesn't work for me. 
The deployment issue is being looked at by bluemix toolchain team.

**Comment by chanskw** [comment]
Thank you!  If you can chase this for us.. that will be great! : )
